In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
from mp1_toolkits.mplot3d import Axes3D 

ModuleNotFoundError: No module named 'mp1_toolkits'

In [8]:
a= [1,3,4.5]
b=a
a,b=np.meshgrid(a,b)
print(a)
print(b)

[[1.  3.  4.5]
 [1.  3.  4.5]
 [1.  3.  4.5]]
[[1.  1.  1. ]
 [3.  3.  3. ]
 [4.5 4.5 4.5]]


In [ ]:
fig = plt.figure()
axes = fig.gca(projection ='3d')
axes.plot_surface(a,b,a**2+b**2)
plt.show()