In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3,4])
x.shape

(4,)

In [24]:
x = np.array([[4,5,6],[5,6,7],[6,5,6]])
x.shape

(3, 3)

In [26]:
t = np.array([[[4,5,6],[5,6,7],[6,5,6]]])
t.shape


(1, 3, 3)

In [33]:
xt=np.transpose(x)
print(x)
print(xt)
y = x.reshape((-1,1))
print(y)
np.transpose(y)

[[4 5 6]
 [5 6 7]
 [6 5 6]]
[[4 5 6]
 [5 6 5]
 [6 7 6]]
[[4]
 [5]
 [6]
 [5]
 [6]
 [7]
 [6]
 [5]
 [6]]


array([[4, 5, 6, 5, 6, 7, 6, 5, 6]])

In [38]:
l = [1,2,3,4]
l = np.array(l)
l = l**2
l

array([ 1,  4,  9, 16], dtype=int32)

In [45]:
a = np.array([[1,2], [5,6]])

In [46]:
b = np.array([[3,4], [7,8]])

In [47]:
print(a)
print(b)

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [49]:
a.shape

(2, 2)

In [50]:
b.shape

(2, 2)

In [51]:
c = np.dot(a,b)
c

array([[17, 20],
       [57, 68]])

In [55]:
y = np.eye(2)
y = y*2
y =y+1

In [56]:
c

array([[17, 20],
       [57, 68]])

In [57]:
print(c*y)

[[ 51.  20.]
 [ 57. 204.]]


In [63]:
x = np.array([-1,3,5,6])
lp2 = np.linalg.norm(x)
print(lp2)

8.426149773176359


In [64]:
lp2 = np.linalg.norm(x,ord=1)
lp2


15.0

In [66]:
lp2 = np.linalg.norm(x,ord=np.inf)
lp2

6.0